#!/bin/bash

cd "/home/sakthi/projects/rag" || exit


if ! docker inspect -f '{{.State.Running}}' qdrant_research >/dev/null 2>&1; then
    docker start qdrant_research || docker run -d --name qdrant_research -p 6333:6333 -p 6334:6334 -v qdrant_storage:/qdrant/storage qdrant/qdrant:latest
fi

if ! docker inspect -f '{{.State.Running}}' grobid >/dev/null 2>&1; then
    docker start grobid || docker run -d --name grobid -p 8070:8070 -p 8071:8071 lfoppiano/grobid:0.8.0
fi

sleep 3

if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

python3 multihop_rag.py "$@"
